version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'rx'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'rx'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rx'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rx'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db1:/var/lib/mysql1
# Names our volume
volumes:
  my-db1:
